format_version: "13"
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: other
workflows:
  primary:
    steps:
    - bundle::Step_bundle: {}
    - git-clone@8: {}
    - bundle::Step_bundle: {}
    - git-clone@8: {}
    triggers:
      push:
      - branch: main
      pull_request:
      - source_branch: '*'
    before_run:
    - sdvdsasd
    meta:
      bitrise.io:
        stack: linux-docker-android-22.04
  sdvdsasd: {}
meta:
  bitrise.io:
    stack: osx-xcode-16.0.x
app:
  envs:
  - foo: 1
    opts:
      is_expand: false
pipelines:
  dsfzxc:
    workflows:
      primary: {}
      sdvdsasd:
        depends_on:
        - primary
step_bundles:
  Step_bundle:
    steps:
    - deploy-to-bitrise-io@2: {}
