---
format_version: "13"
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
  primary:
    steps:
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@8: {}
    - deploy-to-bitrise-io@2: {}
meta:
  bitrise.io:
    machine_type_id: standard
trigger_map:
- workflow: primary
  push_branch: main
- workflow: primary
  pull_request_source_branch: "*"
