---
workflows:
  primary:
  steps:
  - activate-ssh-key@4:
      run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
  - git-clone@8: {}
  - deploy-to-bitrise-io@2: {}
meta:
  bitrise.io:
trigger_map:
- workflow: primary
  push_branch: main
- workflow: primary
  pull_request_source_branch: "*"
